[package]
name = "enhanced_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_enhanced_lib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
rand = "0.8.4"
regex = "1.10.2"
